### ISSUE TITLE
キャラクターデザイン原案

### ISSUE THREAD

**Issue by yamaso** [CreaGameProject/mission_2019#1]
内容
---
CGPちゃんの3Dモデルを作成するため、まず2Dのデザインをします。そのデザイン（清書）を描く前に、デザインコンセプトを募集したいと思います！！！！！

**Comment by ishimaruTakato** [comment]
自分のCGPちゃん案です
![CGP案](https://user-images.githubusercontent.com/39999911/67469561-5a72c680-f687-11e9-980d-ded67659aa85.png)

**Comment by OmoriItsuki** [comment]
### テスト
>こんなことができるよ
[ここ参考](https://www.asobou.co.jp/blog/bussiness/markdown)

**Comment by fujitaiori416** [comment]
CGPちゃんデザイン案です
![cgpchan](https://user-images.githubusercontent.com/44431868/67469726-91e17300-f687-11e9-86b4-423560abd98e.jpg)

**Comment by satousan-55** [comment]
できたよ
![佐藤のやつ](https://user-images.githubusercontent.com/56956384/67469743-960d9080-f687-11e9-9a40-b9f61babca0c.png)

**Comment by chikazawa24** [comment]
![cgp](https://user-images.githubusercontent.com/56956326/67469835-b50c2280-f687-11e9-9a01-1f0ec481df52.png)
ほい。
