### ISSUE TITLE
GUI系統のデザイン

### ISSUE THREAD

**Issue by SatoshiTsuda0403** [CreaGameProject/mission_2019#10]
動画内で必要になる素材のデザインをお願いします。

---

素材：
- プリミティブパレット
- エラー表示
- プログラミングモニター（中央・右）

参考：
- [動きのコンテ](https://docs.google.com/document/d/1sH85S0FXel6O8ExwJaDTiuOcsj7yVE8A4zdV0Zx5R-w/edit)
- [デザイン参考画像](https://drive.google.com/drive/u/0/folders/14X_GBmXChz5YRkzYBvNsYYJ6c1Pwpo6J)
---

青色ベースの近未来的なデザインにしたいと考えています。実態のあるモニターではなく、空中に浮かぶホログラムのイメージです。参考画像を参照してください。
ネオコトづくり室に合うデザインのものをお願いしたいです。プログラミングモニターは、書かれている文字は、デザイン（フォントや色、大きさなど）が分かれば適当で大丈夫です。

**Comment by SatoshiTsuda0403** [comment]
ネオコトづくり室のデザイン画
![neo](https://user-images.githubusercontent.com/56957326/68450611-03e0bd00-022f-11ea-9c6f-a7cb265fe4f2.JPG)

**Comment by chikazawa24** [comment]
@SatoshiTsuda0403 
https://drive.google.com/drive/u/0/folders/1NiwCQQqn0W8mdrsPxjfd1jvI9mCw6lNJ
とりあえず作ってみました。リテイクお待ちしてます。

**Comment by SatoshiTsuda0403** [comment]
@chikazawa24 
エラーメッセージの方はOKです。下のもので行こうと思います。
![error6](https://user-images.githubusercontent.com/56957326/69843770-4e90aa80-12ac-11ea-857b-569f6f69eddf.png)

プログラミングモニターの方ですが、現在の案では少々簡素すぎるイメージですので、中央・右ともにディテールアップをお願いしたく思います。
どちらのモニターも四角形で、下図の矢印のような、選択タブ（上）やスクロールバー（右）の追加をお願いします💦
![63d0cdf669c1d22c0e820e97cc0239b2](https://user-images.githubusercontent.com/56957326/69843927-032acc00-12ad-11ea-806f-aac5d095a596.png)

**Comment by SatoshiTsuda0403** [comment]
プリミティブパレットですが、イメージが複雑で難しいものになりそうなので、私自身がデザインすることにしてもいいでしょうか...?

**Comment by chikazawa24** [comment]
全然大丈夫🙆‍♂️
よろしくお願いしやす🤲

**Comment by chikazawa24** [comment]
あとエフェクト関係のタスクについて詳細決まり次第教えてもらえると嬉しいです😃

**Comment by SatoshiTsuda0403** [comment]
了解です

**Comment by chikazawa24** [comment]
![re](https://user-images.githubusercontent.com/56956326/70203948-12ed5900-1762-11ea-95c7-f544ec6bfcd8.png)
![re2](https://user-images.githubusercontent.com/56956326/70203950-12ed5900-1762-11ea-9542-93d8e3ffc847.png)
中央モニターの配置（？）を考え中。
配色・サイズ・整列とかはとりあえず気にせずに意見が欲しいっす。

**Comment by chikazawa24** [comment]
![re2](https://user-images.githubusercontent.com/56956326/70204111-aa52ac00-1762-11ea-807a-9e13f199c332.png)
周りが見にくかったので再掲。（すまぬ）

**Comment by SatoshiTsuda0403** [comment]
かなりいい感じです！細かい調整が完了次第このデザインで行こうと思います。

**Comment by chikazawa24** [comment]
![error](https://user-images.githubusercontent.com/56956326/70592826-59d5c580-1c1e-11ea-9bbe-55045e2b403f.png)
遅くなって申し訳ない。タブとかいろいろとサイズ調整してます。確認お願いします

**Comment by chikazawa24** [comment]
![error2](https://user-images.githubusercontent.com/56956326/70592906-999cad00-1c1e-11ea-86c3-965e480888eb.png)
外枠部分が見にくいので枠線を消してないものも。
（一応、想定では外枠なしです）

**Comment by SatoshiTsuda0403** [comment]
ありがとうございます。こちらのデザインで行きます。
