### ISSUE TITLE
オブジェクト系統のデザイン

### ISSUE THREAD

**Issue by SatoshiTsuda0403** [CreaGameProject/mission_2019#11]
動画内で必要になる素材のデザイン

---

素材：
- コンテのシーン１で完成するオブジェクト
- ゲームシーン

参考：
- [動きのコンテ](https://docs.google.com/document/d/1sH85S0FXel6O8ExwJaDTiuOcsj7yVE8A4zdV0Zx5R-w/edit)
- [デザイン参考画像](https://drive.google.com/drive/u/0/folders/1r1EapMUTVHvKbsvrjtX5VVyLAq0rrua2)

---

ゲームシーンとシーン１で完成するオブジェクトですが、ディテールの細かいものではなく、単純な形状の組み合わせを考えています。サンドボックスにあるような、「プリミティブ（四角形、円柱、円などの簡単な形）を組み合わせて作られたデザイン」のイメージです。
シーン１で完成するオブジェクトは、CGPちゃんが作るゲームの 主人公 に当たるキャラクターです。可愛らしい見た目が好ましいです。
詳細は、参考画像を参照してください。

**Comment by satousan-55** [comment]
![案達](https://user-images.githubusercontent.com/56956384/70214194-52c23980-177e-11ea-9188-a1a44d36ab30.jpg)

**Comment by satousan-55** [comment]
案挙げてみてます

**Comment by SatoshiTsuda0403** [comment]
ありがとうございます。

**Comment by satousan-55** [comment]
遅くなりました！本日中にゲームシーンのデザインあげますのでもう少々お待ちください！！！

**Comment by satousan-55** [comment]
![イメージ](https://user-images.githubusercontent.com/56956384/70630797-849c3a00-1c6f-11ea-9690-1021a638e754.png)

**Comment by satousan-55** [comment]
イメージ案描いてみました。
