### ISSUE TITLE
ツール系統のデザイン

### ISSUE THREAD

**Issue by SatoshiTsuda0403** [CreaGameProject/mission_2019#12]
動画内で必要になる素材のデザイン

---

素材：
- ワークスペース
- ペン

参考：
- [動きのコンテ](https://docs.google.com/document/d/1sH85S0FXel6O8ExwJaDTiuOcsj7yVE8A4zdV0Zx5R-w/edit)
- [デザイン参考画像（ツール系統）](https://drive.google.com/drive/u/0/folders/1sOSbYUHzhySbuushGRp_FIHvff_gnC7G)
- [デザイン参考画像（GUI系統）](https://drive.google.com/drive/u/0/folders/14X_GBmXChz5YRkzYBvNsYYJ6c1Pwpo6J)

---

ワークスペースは、GUI系統に似たデザインにしたいと考えています。オブジェクトを作成するための、ホログラム式作業台という設定です。必要であれば、GUI系統の参考画像も参照してください。また、ツール系統の参考画像ですが、画像内の 赤い〇印 の位置に、作成中のオブジェクトがあるイメージです。
ペンは、太めで曲線的なデザインを考えています。色は白をベースとした配色でお願いしたいです。

**Comment by T-makinose** [comment]
![image](https://user-images.githubusercontent.com/45839576/69830080-4877db00-1266-11ea-81a6-8b4bb3a297ba.png)
　現在の進捗

**Comment by T-makinose** [comment]
ペンの調子が悪いため基本長方形で描画していますが、まだまだ調整や加える点多くありそうな感じです。
もし見たらアドバイスオナシャス
@SatoshiTsuda0403

**Comment by T-makinose** [comment]
![Uploading image.png…]()

**Comment by T-makinose** [comment]
![image](https://user-images.githubusercontent.com/45839576/69830573-ce952100-1268-11ea-94f1-749e6cc8e253.png)

**Comment by T-makinose** [comment]
めっちゃ勘違いしてたふしあるので本日中に練り直します。

**Comment by T-makinose** [comment]
@SatoshiTsuda0403

**Comment by SatoshiTsuda0403** [comment]
了解しました。

**Comment by T-makinose** [comment]
![image](https://user-images.githubusercontent.com/45839576/70392626-51ff0100-1a25-11ea-86ba-ba4d117bc6f8.png)
こんな感じ？？
@SatoshiTsuda0403

**Comment by T-makinose** [comment]
![案　作業台](https://user-images.githubusercontent.com/45839576/70695652-8a445f00-1d05-11ea-8ab1-f877c1535d0c.jpg)
![イラスト](https://user-images.githubusercontent.com/45839576/70695661-8e707c80-1d05-11ea-9d2e-2d6e7bb0ab20.jpg)

**Comment by SatoshiTsuda0403** [comment]
ありがとうございます。こちらクローズします。
