### ISSUE TITLE
置物系統のデザイン

### ISSUE THREAD

**Issue by SatoshiTsuda0403** [CreaGameProject/mission_2019#14]
動画内で必要になる素材のデザイン

---

素材：
- 折り畳み式ホワイトボード
- 棚
- ロッカー

参考：
- [デザイン参考画像](https://drive.google.com/drive/u/0/folders/1wWKiso8H5e1kX276uaKXS2rWRp8iT4zo)
- ネオコトづくり室
![neo](https://user-images.githubusercontent.com/56957326/68469174-03f7b180-025d-11ea-8ec8-06a86a03de94.JPG)

---

元々コトづくり室にある棚やロッカーは、参考画像にアップしているので参照してください。基本的には、形を大きく変えず、ネオコトづくり室に合わせたデザインに改変する感じでお願いします。折り畳み式ホワイトボードも同様です。

**Comment by ishimaruTakato** [comment]
一応書いた。
置物系統の中の　案ファイル　に入ってる

**Comment by SatoshiTsuda0403** [comment]
ありがとうございます！
確認しました。この案で行こうと思います。
