### ISSUE TITLE
CGPちゃんのデザイン画の完成

### ISSUE THREAD

**Issue by SatoshiTsuda0403** [CreaGameProject/mission_2019#3]
内容
---
CGPちゃんの草案に基づいて、最終的なデザイン画（清書）をお願いします。

**仕様**
CGPちゃんの設定
- 高校生～大学生の年齢
- 元気で無邪気な印象
- 和歌山要素は特に入れない

デザイン構成
- 佐藤さんのデザイン草案をベースに作成
- スカート部分は、短パンに変更
- 服と髪の配色は、藤田さんのデザインに

**Comment by SatoshiTsuda0403** [comment]
<img src= "https://i.gyazo.com/thumb/1000/d2947f4516e81a6daff4763211d08da8-png.jpg" alt="参考画像1" title="参考画像1">

<img src= "https://i.gyazo.com/bdda4ba46b970bb56ebc3342a27c4beb.png" alt="参考画像2" title="参考画像2">

**Comment by fujitaiori416** [comment]
こんな感じでどうでしょうか…！
![cgpchan](https://user-images.githubusercontent.com/44431868/68310883-16a2a700-00f4-11ea-879c-8857c1d14a29.jpg)
