### ISSUE TITLE
素材のデザイン担当

### ISSUE THREAD

**Issue by m-date0504** [CreaGameProject/mission_2019#9]
# 動画内の素材の担当をわけてほしいです

- パレット
- プリミティブ4種
- シーン1で完成するオブジェクト
- ゲームシーンに既成のオブジェクト
- エラー
- ペン
- 中央モニター・右モニター

動画のフローを説明するのでそのあと担当したいところ書き込んでください

**Comment by m-date0504** [comment]
「俺はここをやるぜ！！！」的な

**Comment by SatoshiTsuda0403** [comment]
いくつかまとめてデザインしてほしい物があります。

- GUI系統
　- プリミティブパレット
　- エラー表示
　- プログラミングモニター（中央・右）
- オブジェクト系統
　- シーン1で完成するオブジェクト
　- ゲームシーンに既成のオブジェクト
- ツール系
　- ワークスペース
　- ペン

**Comment by SatoshiTsuda0403** [comment]
- ネオコトづくり室系統
　- 椅子（大型・小型の２種類）
　- 窓（ミストポリッドスクリーン）
